name: 04 - using action
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run : ls  
            - name: Setup Node
              uses: actions/setup-nodes@v3
              with:
                node-version: '20.x'
            - name: install Dependencies
              run: npm ci      


        

        