name: 06 -Contexts
on: 
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Display Event Information
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
    - name: Retrieve Variable
      run: |
        echo "Variable value: ${{ vars.MY_VAR }}"    